name: aterni_usb_eth_printing
description: A Flutter plugin for USB and Ethernet printer support
version: 0.0.1
homepage: https://github.com/midhunsankar23/aterni_usb_eth_printing

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.aterni.aterni_usb_eth_printing
        pluginClass: AterniUsbEthPrintingPlugin
